version: "3.7"
services:

  validator-1:
    ports:
      - "9944:9944"
      - "19933:9933"
    volumes:
      - ./chain-spec:/chain-spec
    image: deeper-chain/deeper-chain:latest
    networks:
      - internet
    command:
      - "deeper-chain"
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000001"
      - "--base-path"
      - "/tmp"
      - "--chain=/chain-spec/local-dev-raw-10.json"
      - "--port"
      - "30333"
      - "--validator"
      - "--bootnodes"
      - "/dns/validator-2/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      # Not only bind to localhost.
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      # - "--log"
      # - "sub-libp2p=trace"
      - "--no-telemetry"
      - "--rpc-cors"
      - "all"
      - "--rpc-methods=unsafe"
      - "--pool-limit"
      - "1000000"
      - "--pool-kbytes"
      - "20480000"

  validator-2:
    image: deeper-chain/deeper-chain:latest
    ports:
      - "9945:9944"
      - "19934:9933"
    volumes:
      - ./chain-spec:/chain-spec
    networks:
      - internet
    command:
      - "deeper-chain"
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000002"
      - "--base-path"
      - "/tmp"
      - "--chain=/chain-spec/local-dev-raw-10.json"
      - "--port"
      - "30333"
      - "--validator"
      - "--bootnodes"
      - "/dns/validator-1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--no-telemetry"
      - "--rpc-cors"
      - "all"
      # Not only bind to localhost.
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      # - "--log"
      # - "sub-libp2p=trace"
      - "--rpc-methods=unsafe"
      - "--pool-limit"
      - "1000000"
      - "--pool-kbytes"
      - "20480000"

  validator-3:
    image: deeper-chain/deeper-chain:latest
    ports:
      - "9946:9944"
      - "19935:9933"
    volumes:
      - ./chain-spec:/chain-spec
    networks:
      - internet
    command:
      - "deeper-chain"
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000003"
      - "--base-path"
      - "/tmp"
      - "--chain=/chain-spec/local-dev-raw-10.json"
      - "--port"
      - "30333"
      - "--validator"
      - "--bootnodes"
      - "/dns/validator-1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--bootnodes"
      - "/dns/validator-2/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      - "--no-telemetry"
      - "--rpc-cors"
      - "all"
      # Not only bind to localhost.
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      # - "--log"
      # - "sub-libp2p=trace"
      - "--rpc-methods=unsafe"
      - "--pool-limit"
      - "1000000"
      - "--pool-kbytes"
      - "20480000"

  validator-4:
    image: deeper-chain/deeper-chain:latest
    ports:
      - "9947:9944"
      - "19936:9933"
    volumes:
      - ./chain-spec:/chain-spec
    networks:
      - internet
    command:
      - "deeper-chain"
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000004"
      - "--base-path"
      - "/tmp"
      - "--chain=/chain-spec/local-dev-raw-10.json"
      - "--port"
      - "30333"
      - "--validator"
      - "--bootnodes"
      - "/dns/validator-1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--bootnodes"
      - "/dns/validator-2/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      - "--no-telemetry"
      - "--rpc-cors"
      - "all"
      # Not only bind to localhost.
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      # - "--log"
      # - "sub-libp2p=trace"
      - "--rpc-methods=unsafe"
      - "--pool-limit"
      - "1000000"
      - "--pool-kbytes"
      - "20480000"

  validator-5:
    image: deeper-chain/deeper-chain:latest
    ports:
      - "9948:9944"
      - "19937:9933"
    volumes:
      - ./chain-spec:/chain-spec
    networks:
      - internet
    command:
      - "deeper-chain"
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000005"
      - "--base-path"
      - "/tmp"
      - "--chain=/chain-spec/local-dev-raw-10.json"
      - "--port"
      - "30333"
      - "--validator"
      - "--bootnodes"
      - "/dns/validator-1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--bootnodes"
      - "/dns/validator-2/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      - "--no-telemetry"
      - "--rpc-cors"
      - "all"
      # Not only bind to localhost.
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      # - "--log"
      # - "sub-libp2p=trace"
      - "--rpc-methods=unsafe"
      - "--pool-limit"
      - "1000000"
      - "--pool-kbytes"
      - "20480000"

  validator-6:
    image: deeper-chain/deeper-chain:latest
    ports:
      - "9949:9944"
      - "19938:9933"
    volumes:
      - ./chain-spec:/chain-spec
    networks:
      - internet
    command:
      - "deeper-chain"
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000006"
      - "--base-path"
      - "/tmp"
      - "--chain=/chain-spec/local-dev-raw-10.json"
      - "--port"
      - "30333"
      - "--validator"
      - "--bootnodes"
      - "/dns/validator-1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--bootnodes"
      - "/dns/validator-2/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      - "--no-telemetry"
      - "--rpc-cors"
      - "all"
      # Not only bind to localhost.
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      # - "--log"
      # - "sub-libp2p=trace"
      - "--rpc-methods=unsafe"
      - "--pool-limit"
      - "1000000"
      - "--pool-kbytes"
      - "20480000"

  validator-7:
    image: deeper-chain/deeper-chain:latest
    ports:
      - "9950:9944"
      - "19939:9933"
    volumes:
      - ./chain-spec:/chain-spec
    networks:
      - internet
    command:
      - "deeper-chain"
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000007"
      - "--base-path"
      - "/tmp"
      - "--chain=/chain-spec/local-dev-raw-10.json"
      - "--port"
      - "30333"
      - "--validator"
      - "--bootnodes"
      - "/dns/validator-1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--bootnodes"
      - "/dns/validator-2/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      - "--no-telemetry"
      - "--rpc-cors"
      - "all"
      # Not only bind to localhost.
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      # - "--log"
      # - "sub-libp2p=trace"
      - "--rpc-methods=unsafe"
      - "--pool-limit"
      - "1000000"
      - "--pool-kbytes"
      - "20480000"

  validator-8:
    image: deeper-chain/deeper-chain:latest
    ports:
      - "9951:9944"
      - "19940:9933"
    volumes:
      - ./chain-spec:/chain-spec
    networks:
      - internet
    command:
      - "deeper-chain"
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000008"
      - "--base-path"
      - "/tmp"
      - "--chain=/chain-spec/local-dev-raw-10.json"
      - "--port"
      - "30333"
      - "--validator"
      - "--bootnodes"
      - "/dns/validator-1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--bootnodes"
      - "/dns/validator-2/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      - "--no-telemetry"
      - "--rpc-cors"
      - "all"
      # Not only bind to localhost.
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      # - "--log"
      # - "sub-libp2p=trace"
      - "--rpc-methods=unsafe"
      - "--pool-limit"
      - "1000000"
      - "--pool-kbytes"
      - "20480000"

  validator-9:
    image: deeper-chain/deeper-chain:latest
    ports:
      - "9952:9944"
      - "19941:9933"
    volumes:
      - ./chain-spec:/chain-spec
    networks:
      - internet
    command:
      - "deeper-chain"
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000009"
      - "--base-path"
      - "/tmp"
      - "--chain=/chain-spec/local-dev-raw-10.json"
      - "--port"
      - "30333"
      - "--validator"
      - "--bootnodes"
      - "/dns/validator-1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--bootnodes"
      - "/dns/validator-2/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      - "--no-telemetry"
      - "--rpc-cors"
      - "all"
      # Not only bind to localhost.
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      # - "--log"
      # - "sub-libp2p=trace"
      - "--rpc-methods=unsafe"
      - "--pool-limit"
      - "1000000"
      - "--pool-kbytes"
      - "20480000"

  validator-10:
    image: deeper-chain/deeper-chain:latest
    ports:
      - "9953:9944"
      - "19942:9933"
    volumes:
      - ./chain-spec:/chain-spec
    networks:
      - internet
    command:
      - "deeper-chain"
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000010"
      - "--base-path"
      - "/tmp"
      - "--chain=/chain-spec/local-dev-raw-10.json"
      - "--port"
      - "30333"
      - "--validator"
      - "--bootnodes"
      - "/dns/validator-1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--bootnodes"
      - "/dns/validator-2/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      - "--no-telemetry"
      - "--rpc-cors"
      - "all"
      # Not only bind to localhost.
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      # - "--log"
      # - "sub-libp2p=trace"
      - "--rpc-methods=unsafe"
      - "--pool-limit"
      - "1000000"
      - "--pool-kbytes"
      - "20480000"

networks:
  network-a:
  internet: