name: build

on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    name: Build
    runs-on: [self-hosted, linux, deeper-chain-runner]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Install Rust toolchain ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-10-21
          components: rustfmt, clippy
          target: wasm32-unknown-unknown
          override: true

      - name: cache dependencies
        uses: Swatinem/rust-cache@v1
      
      - name: Compile
        run: cargo build
