name: coverage

on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  coverage:
    name: Code Coverage
    runs-on: [ubuntu-latest]
    steps:
      - name: update ubuntu system
        run: sudo apt install -y build-essential

      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy
          target: wasm32-unknown-unknown
          override: true

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
