name: style_check

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  style_check:
    name: cargo fmt and 
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Setup rust toolchain
        run: rustup show

      - name: Cargo Fmt Check
        run: cargo fmt --all -- --check

      - name: Cargo Clippy check
        run: SKIP_WASM_BUILD=1 env -u RUSTFLAGS cargo clippy --all-targets